name: CI to Docker Hub

on:
  pull_request:
  push:
    branches:
      - main
      - feature/**

  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest
    container:
      image: node

    steps:
      - uses: actions/checkout@v1
      - name: Install & Tests
        run: |
          npm install
          npm test
