name: Publish

on:
  release:
    types: [published, edited]

jobs:
    test:
        runs-on: ubuntu-latest
        container:
          image: node

        steps:
          - uses: actions/checkout@v1
          - name: Install & Tests
            run: |
              npm install
              npm test

    build:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - name: Check Out Repo
          uses: actions/checkout@v2

        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v1

        - name: Build and push
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            context: ./
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/react_nginx:latest

        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}

        - name: Deploy
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            password: ${{ secrets.SSH_KEY }}
            script: |
              docker kill $(docker ps -q)
              docker system prune -a
              docker pull kastenholt/react_nginx:latest
              docker run -d -p 8002:8002 -e PORT=8002 kastenholt/react_nginx:latest
