name: Publish

on:
  release:
    types: [published, edited]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_KEY }}
          script: |
            docker kill $(docker ps -q)
            docker system prune -a
            docker pull kastenholt/react_nginx:latest
            docker run -d -p 8002:8002 -e PORT=8002 kastenholt/react_nginx:latest
